### ISSUE TITLE
convertTypoScriptArrayToPlainArray() must be of the type array (PHP 7.x Issue?)

### ISSUE THREAD

**Issue by Scunkaneli** [fnagel/generic-gallery#11] opened 2017-04-29 21:36 UTC
Hi!

Using PHP 7.1.4 (I know it is not supported yet, but in another thread you said it's just because you could not test it yet) and Typo3 7.6.18 I get the following error when trying to add the generic-gallery extension to a page:

`Argument 1 passed to TYPO3\CMS\Extbase\Service\TypoScriptService::convertTypoScriptArrayToPlainArray() must be of the type array, null given, called in [redacted]/typo3conf/ext/generic_gallery/Classes/Service/SettingsService.php on line 173`

In error-log, I can see the following additional information:

`TypeError thrown in file [redacted]/typo3_src-7.6.18/typo3/sysext/extbase/Classes/Service/TypoScriptService.php in line 32.`

If I try to edit the page where I added the plugin, this error message is still shown. I have to completly delete the page to eliminate the error. Opening the page via browser just shows a completly empty page.

Of course I'm not sure this is caused by my usage of PHP 7.1.4, but I wasn't able to find another user having the same problem and as PHP 7.1.4 is untested, I guess it has something to do with it.

Edit: I just noticed you live in Germany too, so if you want you can answer in German :)

**Comment by fnagel** [comment] 2017-04-30 13:08
Hey there!

Right, PHP 7.1 is not tested yet but I assume it should work without issues.

Actually there is another user with a similar issue but using PHP 7.0.10, see https://forge.typo3.org/issues/78454 (yes, bot, forge and GH is somehow bad, I already plan to move forge issues to GH). The ticket is missing a solution until now :-/

Please try adding the static TS on root and test if that works for you. There seems to be some issues with the `SettingService` lately. I need to check this but did not have the time yet...

**Comment by Anubiso** [comment] 2017-05-04 10:50
Hey together,

I get the same error in TYPO3 7 LTS (7.6.18) and PHP 7.0.* in composer-mode.

Added the static TS for generic_gallery and bootstrap_example (also directly in the root-template), but can't create a content-element because of the error. The settings retrieved from the SettingService:
`$setup = $this->configurationManager->getConfiguration(
            ConfigurationManagerInterface::CONFIGURATION_TYPE_FULL_TYPOSCRIPT
        );`
don't include plugin.tx_genericgallery. They look incomplete.

**Comment by Anubiso** [comment] 2017-05-05 08:26
intermediate result:

I have now overwritten the generic_gallery TCA, removed the itemsProcFunc-hook and re-added the needed items with TCA.

```
unset($GLOBALS['TCA']['tt_content']['columns']['tx_generic_gallery_predefined']['config']['itemsProcFunc']);
$GLOBALS['TCA']['tt_content']['columns']['tx_generic_gallery_predefined']['config']['items'] = [
    ['Default Gallery', 'gallery'],
    ['Bootstrap Image Slider', 'bootstrap_slider_image'],
];
```

Also see http://stackoverflow.com/a/43789084/5070154 in regards of using TypoScript in the Backend-Context.

**Comment by Scunkaneli** [comment] 2017-05-05 13:13
I haven't had much time to work on the page, so sorry for the delay. 

> Please try adding the static TS on root and test if that works for you. 

I guess you mean including the generic_gallery template in BE? I already did that, so that's not the problem I guess.

@Anubiso Sadly, I can't say much about your intermediate solution, as I'm not sure I understood you correctly (not a typo3 pro here). Am I right, you basicly include the template via command and not via BE?

**Comment by Anubiso** [comment] 2017-05-05 13:32
@Scunkaneli Close - I am also including the TypoScript, but have overwritten the TCA of generic_gallery to remove the hook which tries to read the TypoScript, because there happens the error:
``` 
unset($GLOBALS['TCA']['tt_content']['columns']['tx_generic_gallery_predefined']['config']['itemsProcFunc']); 
```

You can do this in a small extension or in the typo3conf/AdditionalConfiguration.php and with
``` 
$GLOBALS['TCA']['tt_content']['columns']['tx_generic_gallery_predefined']['config']['items'] = [
    ['Default Gallery', 'gallery'],
    ['Bootstrap Image Slider', 'bootstrap_slider_image'],
]; 
``` 
you can statically re-add the items (you have to include all templates which you want to use)

**Comment by Scunkaneli** [comment] 2017-05-05 16:33
Alright, thanks! 
Are all functions of the gallery working with this method?

**Comment by Anubiso** [comment] 2017-05-08 07:52
Yes, would say so - or better said: I haven't found something which doesn't work with his method.

**Comment by Scunkaneli** [comment] 2017-05-13 13:36
Update: After upgrading to CMS 8.7.1 and without changing anything on the configuration nor using the code @Anubiso provided, the error is gone. :)

**Comment by fnagel** [comment] 2017-08-26 10:33
Finally found time to dig into this. Switched back to how TS was generated before the `SettingsService`. Seems to work probably now, regardless where the TS is included (root template, additional template, root page, ...).

Would you mind to test the latest master and give some feedback?

**Comment by Scunkaneli** [comment] 2017-08-26 10:44
I was able to test the master and I can confirm everything I tried worked (showing an existing gallery, creating a new gallery, edit an existing gallery).

Put please keep in mind that, as I already wrote some months ago, the error never occured on CMS 8. So the master did not fix anything for me (as everything was already working with 8), but also did not break anything.

**Comment by fnagel** [comment] 2017-08-26 10:50
@Scunkaneli Wow, that was fast :-D

Ok, thanks for the feedback anyway. I've tested this in 8.7 and was able to reproduce and fix the issue. In 7.6 the error did not occur but the new generation works as expected.

We'll see if anybody else is able to test this probably. There are a two other similar error reports on forge which I've updated too.

**Comment by fnagel** [comment] 2017-11-15 08:48
@Anubiso Any feedback on this issue?

**Comment by mario6097** [comment] 2017-12-17 19:34
Hi

I just tried to install generic-gallery, and run into the error.
I am on a TYPO3 7.6.23, and  PHP version: 5.5.30.
I am not sure whether/how you fixed it, I appreciate your advise.
greetings

**Comment by fnagel** [comment] 2018-01-31 09:56
@mario6097 Which version of GG did you use?

**Comment by fnagel** [comment] 2018-02-16 22:55
@mario6097 Forgot to mention that

> I am not sure whether/how you fixed it (i mean without to update to v.8)

You don't need to update to TYPO3 8.x, just use the current master branch!

**Comment by fnagel** [comment] 2018-04-07 21:43
@mario6097 Any feedback on the current master branch?

**Comment by fnagel** [comment] 2018-11-08 14:20
Closed as no feedback was given.

**Closed by fnagel** 2018-11-08 14:20 UTC
Labels: bug
