### ISSUE TITLE
Typoscript not loading in Plugin content element if all sibling sites are disabled

### ISSUE THREAD

**Issue by benjaminmeissner** [fnagel/generic-gallery#27] opened 2020-01-14 10:01 UTC
**Typo3 Version: 9.5.10**
**Plugin version: 3.0.0**

Folowing Page Tree is given
```
Rootpage
->Subpage 1
->Subpage 2
-->Subsub 1 (Disabled)
-->Subsub 2 (Disabled)
-->Subsub 3 (Disabled)
->Subpage 3
[...]
```

Main Typoscript including generic gallery TS for own templates is applied to Rootpage. All pages (including the disabled ones) contain typoscript settings for Generic gallery if you check Typoscript object browser. 

If you try to add generic gallery to one of the disabled pages, you will get an error (flashmessage) in Plugin Tab of the content element: 
`An error occurred trying to process items for field "Gallery type" (No typoscript settings available.).`  And no templates are available to choose from.

Current fix for me: activating **one** of the subpages, adding gallerys to it and select templates. After this the subpage can be disabled again and plugins wont brake.

Not sure right now if this is plugin or typo3 core related. Other plugins like news don't show this specific behaviour.

**Comment by fnagel** [comment] 2020-01-20 16:52
This is plugin related. Could be caused by the use of TS in the BE. I will check how to solve this...

**Comment by fnagel** [comment] 2020-01-20 17:01
Confirmed in a TYPO3 9.5.11

**Comment by fnagel** [comment] 2020-01-20 17:33
Uhh, missed that you are using version 3 and not version 4 of my extension. Any reason why?

I'm not able to reproduce this in TYPO 9.5 with GG 4.0.0. 

Would you mind updating?

**Comment by benjaminmeissner** [comment] 2020-01-21 08:14
I did miss the release of 4.0.0

The project is in pipeline for half a year now and I did not recheck for updates. I will try to reproduce this with version 4.0.0 and come back to you!

**Comment by benjaminmeissner** [comment] 2020-01-21 08:22
Hey Felix, 

Update went smooth- Not able to reproduce the issue with Plugin version 4.0.0. Thanks for pointing out the version update and also thanks for the great plugin!

Can be closed I guess, but you shall decide

**Comment by fnagel** [comment] 2020-01-27 22:20
Hey Benjamin, thanks for the feedback! Glad it works for you now.

The issue is now documented and we'll see if someone needs this backported.

Closing this for now. Please reopen if needed.

**Closed by fnagel** 2020-01-27 22:20 UTC
